
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='variable-updater',
    version='0.0.1',
    python_requires='==3.*,>=3.7.0',
    author='Rob Wilson',
    author_email='roobert@gmail.com',
    entry_points={"console_scripts": ["variable-updater = variable_updater.variable_updater:main"]},
    packages=['variable_updater', 'variable_updater.bitbucket'],
    package_dir={"": "."},
    package_data={},
    install_requires=['hvac==0.*,>=0.9.6', 'pyyaml==5.*,>=5.2.0', 'requests==2.*,>=2.22.0'],
    extras_require={"dev": ["black==19.*,>=19.10.0", "pylint==2.*,>=2.4.4"]},
)
